### ISSUE TITLE
`UnboundLocalError: local variable 'req_content' referenced before assignment`

### ISSUE THREAD

**Issue by astrojuanlu** [SMAT-Lab/SnifferDog#8]
After fixing gh-7 locally, I encountered another error:

```
Traceback (most recent call last):
  File "/home/juanlu/Projects/Other/SnifferDog/lib_ver_producer.py", line 210, in <module>
    main()
  File "/home/juanlu/Projects/Other/SnifferDog/lib_ver_producer.py", line 206, in main
    print(req_content)
UnboundLocalError: local variable 'req_content' referenced before assignment
```

**Comment by astrojuanlu** [comment]
Well, this was my fault 🙃 please ignore

**Comment by astrojuanlu** [comment]
Can happen if the `all()` condition at the beginning is not met:

https://github.com/SMAT-Lab/SnifferDog/blob/2a855ec14dcca4d8b939284dd4f70e75a9518f26/lib_ver_producer.py#L183-L186

(see also gh-9)
